import type { Metadata } from 'next';
import { Jost, Montserrat } from 'next/font/google';
import './globals.css';
import CartDataProvider from '@/components/custom/cart/CartDataProvider';
import ShopifyDataProvider from '@/components/custom/ShopifyDataProvider';
import Header from '@/components/custom/header/Header';
import { Toaster } from '@/components/ui/sonner';

const heading = Jost({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600'],
  variable: '--font-heading',
});

const body = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600'],
  variable: '--font-body',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${heading.variable} ${body.variable} font-body`}>
        <ShopifyDataProvider>
          <CartDataProvider>
            <Header />
            {children}
            <Toaster
              position="top-center"
              richColors={true}
              offset={10}
              duration={3000}
            />
          </CartDataProvider>
        </ShopifyDataProvider>
      </body>
    </html>
  );
}
